module.exports = {
  parser: 'babel-eslint',
  extends: [
    './rules/base',
    './rules/import',
    './rules/jest',
    './rules/jsx-a11y',
    './rules/react',
  ].map(require.resolve),
  env: {
    browser: true,
    node: true,
  },
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module',
    ecmaFeatures: {
      arrowFunctions: true,
      blockBindings: true,
      classes: true,
      defaultParams: true,
      destructuring: true,
      experimentalObjectRestSpread: true,
      forOf: true,
      generators: true,
      jsx: true,
      modules: true,
      objectLiteralComputedProperties: true,
      objectLiteralDuplicateProperties: true,
      objectLiteralShorthandMethods: true,
      objectLiteralShorthandProperties: true,
      restParams: true,
      spread: true,
      superInFunctions: true,
      templateStrings: true,
    },
  },
  globals: {
    System: true,
    Promise: true,
    document: true,
    window: true,
  },
  rules: {},
}
